server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
          filters:
            - RewritePath=/delivery/(?<segment>.*), /api/delivery/${segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /api/product/${segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /api/user/${segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /api/order/${segment}
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /api/payment/${segment}
        - id: saga-service
          uri: lb://saga-service
          predicates:
            - Path=/saga/**
          filters:
            - RewritePath=/saga/(?<segment>.*), /api/saga/${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/