server:
  port: 8020

spring:
  application:
    name: saga-service
  datasource:
    url: jdbc:postgresql://ep-wispy-surf-a80elzgi-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_frXpem0gCz4a
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-saga
      auto-offset-reset: earliest
      enable-auto-commit: true
    admin:
      auto-create: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

my_secret_key: "thisismysecretkeyanditshouldbeverylonganditshouldnotbehardcoded"
myExpirationTime: 3600000

info:
  app:
    name: "Delivery Service"
    description: "Delivery Service for E-Commerce Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
#  endpoint:
#    health:
#      show-details: always
#      probes:
#        enabled: true
#  health:
#    db:
#      enabled: true
#    diskspace:
#      enabled: true
#    mongo:
#      enabled: false
#    redis:
#      enabled: false
#    kafka:
#      enabled: false
#    rabbit:
#      enabled: false
#    livenessState:
#      enabled: true
#    readinessState:
#      enabled: true

logging:
  level:
    org:
      apache:
        kafka: INFO

# ================== SWAGGER ==================